-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brand
(
    brand_id integer NOT NULL DEFAULT nextval('brand_brand_id_seq'::regclass),
    brand_name character varying(100) COLLATE pg_catalog."default",
    company character varying(100) COLLATE pg_catalog."default",
    logo_file character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT brand_pkey PRIMARY KEY (brand_id),
    CONSTRAINT brand_brand_name_key UNIQUE (brand_name)
);

CREATE TABLE IF NOT EXISTS public.color
(
    color_id integer NOT NULL DEFAULT nextval('color_color_id_seq'::regclass),
    color_name character varying(100) COLLATE pg_catalog."default",
    color_code character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT color_pkey PRIMARY KEY (color_id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL DEFAULT nextval('product_product_id_seq'::regclass),
    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    color_id integer,
    style_id integer,
    brand_id integer,
    serial_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    product_description character varying(100) COLLATE pg_catalog."default",
    stock_onhand integer DEFAULT 0,
    retail_price numeric(8, 2) DEFAULT 0.0,
    CONSTRAINT product_pkey PRIMARY KEY (product_id),
    CONSTRAINT product_serial_number_key UNIQUE (serial_number)
);

CREATE TABLE IF NOT EXISTS public.style
(
    style_id integer NOT NULL DEFAULT nextval('style_style_id_seq'::regclass),
    style_name character varying(100) COLLATE pg_catalog."default",
    style_code character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT style_pkey PRIMARY KEY (style_id)
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_brand_id_fkey FOREIGN KEY (brand_id)
    REFERENCES public.brand (brand_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_color_id_fkey FOREIGN KEY (color_id)
    REFERENCES public.color (color_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_style_id_fkey FOREIGN KEY (style_id)
    REFERENCES public.style (style_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;